### ISSUE TITLE
Latest Plex version

### ISSUE THREAD

**Issue by robertronq** [johnypony3/rpi-docker-plex#2]
Thank you very much for keeping this image updated. 
I just wanted to ask if and when the image will get updated to the latest Plex version "Version 1.12.0.4829". Thank you very much.

**Comment by Wangxingdong** [comment]
https://github.com/appliedtopology/javaplex/releases

**Comment by robertronq** [comment]
Hi. Any chance you can update to the newest image 1.12.3.4973 ?  Thank you !!

**Comment by johnypony3** [comment]
i apologize! i wasnt aware that someone forked this. i will be more diligent on pushing new versions.
i have added a python script that will orchestrate the build and push.
crontab is set this to run on a schedule daily at PST noon.
**caveat:** this solution is brittle. it only runs on my machine, so it will stop working __probably__.
script ran and latest version has been updated: 1.12.3.4973-215c28d86
closing issue
